### ISSUE TITLE
The doc link in repo description is wrong.

### ISSUE THREAD

**Issue by Claiyre** [imcuttle/edam#4]
404

**Comment by imcuttle** [comment]
Are you refer to the link: https://imcuttle.github.io/edam/index_zh ?
It works fine!

**Comment by Claiyre** [comment]
emmm?
![image](https://user-images.githubusercontent.com/18069718/40617282-7a2f6dfe-62c0-11e8-8141-64762939f8b0.png)

**Comment by imcuttle** [comment]
😆, The reason of the presentation is that my blog had used service worker. However, I dropped the sw now.

Maybe you should clear my blog's cache of your browser, then refresh the site.

**Comment by Claiyre** [comment]
It works! Thanks
